// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_hour;
lv_obj_t * ui_year;
lv_obj_t * ui_minute;
lv_obj_t * ui_MMM;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Container1;
lv_obj_t * ui_day;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label13;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_ButtonDemo;
void ui_event_ledonbutton(lv_event_t * e);
lv_obj_t * ui_ledonbutton;
void ui_event_ledoffbutton(lv_event_t * e);
lv_obj_t * ui_ledoffbutton;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_ArcDemo;
void ui_event_Arc(lv_event_t * e);
lv_obj_t * ui_Arc;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_SliderDemo;
lv_obj_t * ui_Panel1;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_SwitchDemo;
lv_obj_t * ui_TestAreaDemo;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ledonbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        turn_on_led(e);
    }
}

void ui_event_ledoffbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        turn_off_led(e);
    }
}

void ui_event_Arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_arc_set_text_value(ui_Label5, target, "", "%");
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_slider_set_text_value(ui_Label6, target, "", "ph");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
