// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_year;
extern lv_obj_t * ui_minute;
extern lv_obj_t * ui_MMM;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_ButtonDemo;
void ui_event_ledonbutton(lv_event_t * e);
extern lv_obj_t * ui_ledonbutton;
void ui_event_ledoffbutton(lv_event_t * e);
extern lv_obj_t * ui_ledoffbutton;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_ArcDemo;
void ui_event_Arc(lv_event_t * e);
extern lv_obj_t * ui_Arc;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_SliderDemo;
extern lv_obj_t * ui_Panel1;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_SwitchDemo;
extern lv_obj_t * ui_TestAreaDemo;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1163064809);    // assets/Fusion-white.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
