// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -138);
    lv_obj_set_y(ui_hour, -205);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "HH");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0x19C058), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_year, -218);
    lv_obj_set_y(ui_year, -205);
    lv_obj_set_align(ui_year, LV_ALIGN_CENTER);
    lv_label_set_text(ui_year, "YYYY");
    lv_obj_set_style_text_color(ui_year, lv_color_hex(0x19C058), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_year, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_year, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute, -89);
    lv_obj_set_y(ui_minute, -205);
    lv_obj_set_align(ui_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute, "MM");
    lv_obj_set_style_text_color(ui_minute, lv_color_hex(0x19C058), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minute, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MMM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MMM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MMM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MMM, -294);
    lv_obj_set_y(ui_MMM, -205);
    lv_obj_set_align(ui_MMM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MMM, "MMM");
    lv_obj_set_style_text_color(ui_MMM, lv_color_hex(0x19C058), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MMM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MMM, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_width(ui_Container2, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_x(ui_Container2, -173);
    lv_obj_set_y(ui_Container2, -205);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_width(ui_Container3, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_x(ui_Container3, 200);
    lv_obj_set_y(ui_Container3, -205);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_x(ui_Container1, -50);
    lv_obj_set_y(ui_Container1, -205);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, -360);
    lv_obj_set_y(ui_day, -205);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "DD");
    lv_obj_set_style_text_color(ui_day, lv_color_hex(0x19C058), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -115);
    lv_obj_set_y(ui_Label12, -205);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, ":");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 75);
    lv_obj_set_y(ui_Label9, -205);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "255.255.255.255");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x19C058), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -333);
    lv_obj_set_y(ui_Label1, -205);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "-");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -254);
    lv_obj_set_y(ui_Label2, -205);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "-");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -333);
    lv_obj_set_y(ui_Label13, -205);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "-");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 780);
    lv_obj_set_height(ui_TabView1, 400);
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, 30);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabView1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x19C058),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &lv_font_montserrat_16,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_ButtonDemo = lv_tabview_add_tab(ui_TabView1, "Button_Demo");
    lv_obj_set_style_border_color(ui_ButtonDemo, lv_color_hex(0x2D1554), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonDemo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledonbutton = lv_btn_create(ui_ButtonDemo);
    lv_obj_set_width(ui_ledonbutton, 100);
    lv_obj_set_height(ui_ledonbutton, 50);
    lv_obj_set_x(ui_ledonbutton, 300);
    lv_obj_set_y(ui_ledonbutton, 0);
    lv_obj_set_align(ui_ledonbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ledonbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ledonbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ledoffbutton = lv_btn_create(ui_ButtonDemo);
    lv_obj_set_width(ui_ledoffbutton, 100);
    lv_obj_set_height(ui_ledoffbutton, 50);
    lv_obj_set_x(ui_ledoffbutton, 300);
    lv_obj_set_y(ui_ledoffbutton, 70);
    lv_obj_set_align(ui_ledoffbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ledoffbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ledoffbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ButtonDemo);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 296);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "ON");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ButtonDemo);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 300);
    lv_obj_set_y(ui_Label4, 70);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "OFF");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcDemo = lv_tabview_add_tab(ui_TabView1, "Arc_Demo");
    lv_obj_set_style_text_color(ui_ArcDemo, lv_color_hex(0x19C058), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcDemo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc = lv_arc_create(ui_ArcDemo);
    lv_obj_set_width(ui_Arc, 150);
    lv_obj_set_height(ui_Arc, 150);
    lv_obj_set_x(ui_Arc, -291);
    lv_obj_set_y(ui_Arc, -75);
    lv_obj_set_align(ui_Arc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc, 0);
    lv_arc_set_bg_angles(ui_Arc, 180, 0);
    lv_obj_set_style_outline_color(ui_Arc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc, lv_color_hex(0x19C058), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc, lv_color_hex(0x19C058), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Arc);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "0");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x19C058), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_ArcDemo);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -361);
    lv_obj_set_y(ui_Label7, -51);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Min");

    ui_Label8 = lv_label_create(ui_ArcDemo);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -225);
    lv_obj_set_y(ui_Label8, -51);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Max");

    ui_SliderDemo = lv_tabview_add_tab(ui_TabView1, "Slider_Demo");

    ui_Panel1 = lv_obj_create(ui_SliderDemo);
    lv_obj_set_width(ui_Panel1, 273);
    lv_obj_set_height(ui_Panel1, 76);
    lv_obj_set_x(ui_Panel1, -233);
    lv_obj_set_y(ui_Panel1, -113);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider2 = lv_slider_create(ui_Panel1);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, -26);
    lv_obj_set_y(ui_Slider2, 0);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x19C058), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider2, 50, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x19C058), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 101);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "000");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchDemo = lv_tabview_add_tab(ui_TabView1, "Switch_Demo");

    ui_TestAreaDemo = lv_tabview_add_tab(ui_TabView1, "TextArea_Demo");

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_1163064809);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 273
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 99
    lv_obj_set_x(ui_Image3, 295);
    lv_obj_set_y(ui_Image3, -207);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 150);

    lv_obj_add_event_cb(ui_ledonbutton, ui_event_ledonbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ledoffbutton, ui_event_ledoffbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc, ui_event_Arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}
